list_of_obs_train: list_i1_train.txt
list_of_obs_val: list_i1_valid.txt
context: use_this_local.yaml
preprocess: lat_cfg_mf.yaml
band: f090
downsample: 8
chunk_size: 30_000 # notice these depend on the downsampling factor
preload: false
normalize_tod: true
normalize_focal_plane: true
num_workers: 4 # this is per mpi task
num_cache_workers: 32
prefetch_factor: 2
nbin: 40
nmode: 12
fmin: 0.16
fmax: null
d_model: 128
d_latent: 64
d_hidden: 256
n_heads: 4
n_layers: 3
dropout: 0.1
lr: 1.0e-4
lr_min: 1.0e-6
weight_decay: 1.0e-05
grad_clip: 0.5
schedule: cosine
warmup_epochs: 1
batch_size: 12
n_epochs: 100
val_max_batches: 40
full_val_every_n_epochs: 10
val_every_n_steps: 200
log_every_n_steps: 20
output_dir: output/test_gpu_114-obs-train
checkpoint_every_n_epochs: 5
keep_last_n_checkpoints: 3
seed: 66
amp: true
pin_memory: true
